azure:
  free_disk_space: true
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
build_platform:
  linux_aarch64: linux_64
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
idle_timeout_minutes: 120
provider:
  linux_aarch64: default
