github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
azure:
  free_disk_space: true
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
idle_timeout_minutes: 120
os_version:
  linux_64: cos7
  linux_aarch64: cos7
build_platform:
  linux_aarch64: linux_64
provider:
  linux_aarch64: azure
